use WAREHOUSE COMPUTE_WH ;

USE DATABASE SNOWFLAKE_LEARNING_DB ;

CREATE OR REPLACE TABLE GOLD.MONTHLY_SALES AS 
SELECT 
    DATE_TRUNC('MONTH', TRANSACTION_DATE) AS SALES_MONTH ,
    SUM(SALES_PRICE) AS TOTAL_SALES
FROM SILVER.FACT_SALES 
GROUP BY SALES_MONTH ;

SELECT * FROM GOLD.MONTHLY_SALES LIMIT 50;